## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: Deploy WildFly connected to an autonomous database
description: Deploy WildFly connected to an autonomous database
schemaVersion: 1.1.0
version: "20200821"
variableGroups:
  - title: General Configuration
    visible: false
    variables:
    - tenancy_ocid
    - region
    - release
    - public_subnet

  - title: Required Configuration
    visible: true  
    variables:
    - compartment_id
    - jboss_node_count
    - jboss_admin_password
    - ssh_authorized_keys
    - provision_atp
    - atp_admin_password
    - show_advanced
  
  - title: Networking Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
    - vcn_cidr_block
    - prefix

  - title: Load Balancer Configuration
    visible: 
        and:
          - show_advanced
    variables:
    - lb_shape 
    - flex_lb_min_shape
    - flex_lb_max_shape 

  - title: Compute Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
    - jboss_vm_shape
    - jboss_vm_flex_shape_ocpu
    - jboss_vm_flex_shape_mem
    - jboss_admin_username

  - title: JBoss/WildFly Deployment Mode
    visible: 
        and:
          - show_advanced
    variables:
    - domain_mode

  - title: Bastion Optional Configuration
    visible: 
        and:
          - show_advanced
    variables:
    - bastion_vm_shape
    - bastion_vm_flex_shape_ocpu
    - bastion_vm_flex_shape_mem

  - title: Autonomous Database (ATP) Optional Configuration
    visible: 
        and:
          - show_advanced
          - provision_atp
    variables:
    - atp_private_subnet  
    - atp_display_name
    - atp_db_name
    - atp_cpu_core_count
    - atp_storage_tbs
    - atp_autoscaling

  - title: Create a JDBC Datasource Optional Configuration
    visible: 
        and:
          - show_advanced
          - provision_atp
    variables:
    - create_jdbc_ds

  - title: JDBC Connection Optional Configuration
    visible: 
        and:
          - show_advanced
          - provision_atp
          - create_jdbc_ds
    variables:
    - ds_name
    - atp_username
    - atp_password

variables:
  # Hidden variables
  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  ssh_authorized_keys:
    type: oci:core:ssh:publickey
    title: SSH Public Key
    required: true
    description: Public SSH Key to access VM via SSH

  show_advanced:
    type: boolean
    title: "Show advanced options"
    description: "Shows advanced options."
    visible: true
    default: false

  # Exposed variables
  compartment_id:
    type: oci:identity:compartment:id
    title: Network Compartment
    description: The compartment where you want to create the network resources such as Virtual Cloud Network, security lists, route tables and gateways.
    required: true
    default: compartment_ocid

  vcn_cidr_block:
    type: string
    title: VCN CIDR block
    description: The CIDR block for the VCN
    required: true
    default: "10.1.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    
  prefix:
    type: string
    title: Resources Prefix
    description: The prefix to name all resources
    required: true
    default: "jboss"
    pattern: "^[a-z0-9]{1,8}$"

  jboss_node_count:
    title: Node Count
    description: Number of VMs to provision
    type: number
    required: true
    default: 1

  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"


  jboss_vm_shape:
    type: oci:core:instanceshape:name
    title: JBoss/WildFly VM(s) Shape
    description: The shape for the JBoss/WildFly instance(s)
    required: true
    dependsOn:
      compartmentId: ${compartment_id}

  jboss_vm_flex_shape_ocpu:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Optimized3.Flex"

  jboss_vm_flex_shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - jboss_vm_shape 
            - "VM.Optimized3.Flex"

  jboss_admin_username:
    type: string
    title: WildFly Administrator Username
    description: The user name of the admin
    required: true
    default: "admin"
    pattern: "^[a-z]{4,16}$"

  jboss_admin_password:
    type: password
    title: WildFly Administrator Password
    description: The password for the WildFly admin user
    required: true

  bastion_vm_shape:
    type: oci:core:instanceshape:name
    title: Bastion Host VM Shape
    description: The shape for the instances
    required: true
    dependsOn:
      compartmentId: ${compartment_id}

  bastion_vm_flex_shape_ocpu:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Optimized3.Flex"

  bastion_vm_flex_shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - bastion_vm_shape 
            - "VM.Optimized3.Flex"

  provision_atp:
    type: boolean
    title: Provision an Autonomous Database (ATP)
    description: Check to provision an Autonomous Database for Transaction Processing
    required: true
    default: true

  atp_private_subnet:
    type: boolean
    title: Provision ATP in private subnet
    description: Provision an Autonomous Database for Transaction Processing
    required: true
    default: true

  atp_admin_password:
    visible: 
        and:
          - provision_atp
    type: password
    title: Autonomous DB Administrator Password
    description: The password for the admin user (12 to 30 characters [a-zA-Z0-9_@#$!&%]$)
    required: 
         and:
          - provision_atp
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]{11,29}$ 

  atp_display_name:
    type: string
    title: ATP Service Display Name
    description: Name of the ATP service
    required: true
    default: "JBossATP"

  atp_db_name:
    type: string
    title: ATP Database Name
    description: Name of the ATP Database
    required: true
    default: "db"

  atp_cpu_core_count:
    type: number
    title: ATP CPU Core Count
    description: Number of CPU cores to use with ATP
    required: true
    default: 1

  atp_storage_tbs:
    type: number
    title: ATP Storage (in TBs)
    description: Number of TBs of storage to use with ATP
    required: true
    default: 1

  atp_autoscaling:
    type: boolean
    title: Enable ATP Autoscaling
    description: Enable ATP auto-scaling (not available on Free Tier)
    required: true
    default: false

  create_jdbc_ds:
    type: boolean
    title: Create a JDBC Datasource
    description: Create and configure a JDBC datasource for ATP
    required: true

  ds_name:
    type: string
    title: Datasource name
    description: the name of the datasource as found in the JNDI path java:/jdbc/<datasource-name>
    required: true
    default: OracleDS

  atp_username:
    type: string
    title: Autonomous DB JDBC Username
    description: The User for the JDBC connection
    required: true

  atp_password:
    type: password
    title: Autonomous DB JDBC User Password
    description: The password for the JDBC connection user (12 to 30 characters [a-zA-Z0-9@#$!&%]$)
    required: true
    pattern: "^[a-zA-Z0-9@#$!&%]{12,30}$"

  domain_mode:
    type: boolean
    title: Domain Controller mode
    description: Setup as in Domain Controller mode for administration of all servers through a central node
    required: true
    default: true

